module: SwiftBeanCountWealthsimpleMapper
readme: README.md
clean: true
disable_search: true
author: Nef10
author_url: https://github.com/Nef10
root_url: https://Nef10.github.io/SwiftBeanCountWealthsimpleMapper/
github_url: https://github.com/Nef10/SwiftBeanCountWealthsimpleMapper
github_file_prefix: https://github.com/Nef10/SwiftBeanCountWealthsimpleMapper/blob/main
output: ./docs
theme: fullwidth
