name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.app/
    - uses: actions/checkout@master
    - name: Tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: SwiftBeanCountDownloaderApp.xcodeproj
        scheme: SwiftBeanCountDownloaderApp
        destination: platform=macOS
        action: test
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run SwiftLint --strict
        uses: norio-nomura/action-swiftlint@3.2.0
        with:
          args: --strict
